# Word Embeddings Examples

## ABC News Headlines

This is a dataset of ABC news headlines from February 19, 2003 to December 31, 2017. The dataset consists of 1,103,663 headlines.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!pip install gdown
!gdown --id 1CjE34VQMmZWw-QO740gyrNJKCN3O4RdK

Requirement already satisfied: gdown in /usr/local/lib/python3.6/dist-packages (3.6.4)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from gdown) (1.12.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from gdown) (4.41.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from gdown) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (2.9)
Downloading...
From: https://drive.google.com/uc?id=1CjE34VQMmZWw-QO740gyrNJKCN3O4RdK
To: /content/abcnews-date-text.csv
55.4MB [00:00, 171MB/s]

In [ ]:
data = pd.read_csv('abcnews-date-text.csv')

In [ ]:
data.head(50)

    publish_date                                      headline_text
0       20030219  aba decides against community broadcasting lic...
1       20030219     act fire witnesses must be aware of defamation
2       20030219     a g calls for infrastructure protection summit
3       20030219           air nz staff in aust strike for pay rise
4       20030219      air nz strike to affect australian travellers
5       20030219                  ambitious olsson wins triple jump
6       20030219         antic delighted with record breaking barca
7       20030219  aussie qualifier stosur wastes four memphis match
8       20030219       aust addresses un security council over iraq
9       20030219         australia is locked into war timetable opp
10      20030219  australia to contribute 10 million in aid to iraq
11      20030219  barca take record as robson celebrates birthda...
12      20030219                         bathhouse plans move ahead
13      20030219      big hopes for launceston cycling championship
14      20030219             big plan to boost paroo water supplies
15      20030219             blizzard buries united states in bills
16      20030219     brigadier dismisses reports troops harassed in
17      20030219     british combat troops arriving daily in kuwait
18      20030219         bryant leads lakers to double overtime win
19      20030219           bushfire victims urged to see centrelink
20      20030219    businesses should prepare for terrorist attacks
21      20030219    calleri avenges final defeat to eliminate massu
22      20030219            call for ethanol blend fuel to go ahead
23      20030219             carews freak goal leaves roma in ruins
24      20030219                       cemeteries miss out on funds
25      20030219  code of conduct toughens organ donation regula...
26      20030219       commonwealth bank cuts fixed home loan rates
27      20030219             community urged to help homeless youth
28      20030219   council chief executive fails to secure position
29      20030219    councillor to contest wollongong as independent
30      20030219       council moves to protect tas heritage garden
31      20030219           council welcomes ambulance levy decision
32      20030219            council welcomes insurance breakthrough
33      20030219      crean tells alp leadership critics to shut up
34      20030219                 dargo fire threat expected to rise
35      20030219   death toll continues to climb in s korean subway
36      20030219           dems hold plebiscite over iraqi conflict
37      20030219     dent downs philippoussis in tie break thriller
38      20030219               de villiers to learn fate on march 5
39      20030219          digital tv will become commonplace summit
40      20030219      direct anger at govt not soldiers crean urges
41      20030219  dispute over at smithton vegetable processing ...
42      20030219              dog mauls 18 month old toddler in nsw
43      20030219     dying korean subway passengers phoned for help
44      20030219               england change three for wales match
45      20030219  epa still trying to recover chemical clean up ...
46      20030219  expressions of interest sought to build livestock
47      20030219         fed opp to re introduce national insurance
48      20030219                    firefighters contain acid spill
49      20030219              four injured in head on highway crash

### Preprocessing the ABC News Headlines

Preprocessing is an essential part of fitting word vectors. We remove stopwords because we do not want to fit vectors for words that are common across all documents and will not give us much information about meaning. We also want to stem so we are not fitting separate word vectors for words such as "running," "runner," and "run."

In [ ]:
# https://radimrehurek.com/gensim/parsing/preprocessing.html
from gensim.parsing import preprocessing

preprocessing.DEFAULT_FILTERS # notice that if you don't like any of these default filters, you have to piece together your own set of functions
                              # check the documentation for default values

[<function gensim.parsing.preprocessing.<lambda>>,
 <function gensim.parsing.preprocessing.strip_tags>,
 <function gensim.parsing.preprocessing.strip_punctuation>,
 <function gensim.parsing.preprocessing.strip_multiple_whitespaces>,
 <function gensim.parsing.preprocessing.strip_numeric>,
 <function gensim.parsing.preprocessing.remove_stopwords>,
 <function gensim.parsing.preprocessing.strip_short>,
 <function gensim.parsing.preprocessing.stem_text>]

In [ ]:
headlines = preprocessing.preprocess_documents(data['headline_text'])

In [ ]:
headlines # need a list of list for gensim functions

[['aba', 'decid', 'commun', 'broadcast', 'licenc'],
 ['act', 'wit', 'awar', 'defam'],
 ['call', 'infrastructur', 'protect', 'summit'],
 ['air', 'staff', 'aust', 'strike', 'pai', 'rise'],
 ['air', 'strike', 'affect', 'australian', 'travel'],
 ['ambiti', 'olsson', 'win', 'tripl', 'jump'],
 ['antic', 'delight', 'record', 'break', 'barca'],
 ['aussi', 'qualifi', 'stosur', 'wast', 'memphi', 'match'],
 ['aust', 'address', 'secur', 'council', 'iraq'],
 ['australia', 'lock', 'war', 'timet', 'opp'],
 ['australia', 'contribut', 'million', 'aid', 'iraq'],
 ['barca', 'record', 'robson', 'celebr', 'birthdai'],
 ['bathhous', 'plan', 'ahead'],
 ['big', 'hope', 'launceston', 'cycl', 'championship'],
 ['big', 'plan', 'boost', 'paroo', 'water', 'suppli'],
 ['blizzard', 'buri', 'unit', 'state', 'bill'],
 ['brigadi', 'dismiss', 'report', 'troop', 'harass'],
 ['british', 'combat', 'troop', 'arriv', 'daili', 'kuwait'],
 ['bryant', 'lead', 'laker', 'doubl', 'overtim', 'win'],
 ['bushfir', 'victim', 'urg', 'centrelink'],
 ['busi', 'prepar', 'terrorist', 'attack'],
 ['calleri', 'aveng', 'final', 'defeat', 'elimin', 'massu'],
 ['ethanol', 'blend', 'fuel', 'ahead'],
 ['carew', 'freak', 'goal', 'leav', 'roma', 'ruin'],
 ['cemeteri', 'miss', 'fund'],
 ['code', 'conduct', 'toughen', 'organ', 'donat', 'regul'],
 ['commonwealth', 'bank', 'cut', 'fix', 'home', 'loan', 'rate'],
 ['commun', 'urg', 'help', 'homeless', 'youth'],
 ['council', 'chief', 'execut', 'fail', 'secur', 'posit'],
 ['councillor', 'contest', 'wollongong', 'independ'],
 ['council', 'move', 'protect', 'ta', 'heritag', 'garden'],
 ['council', 'welcom', 'ambul', 'levi', 'decis'],
 ['council', 'welcom', 'insur', 'breakthrough'],
 ['crean', 'tell', 'alp', 'leadership', 'critic', 'shut'],
 ['dargo', 'threat', 'expect', 'rise'],
 ['death', 'toll', 'continu', 'climb', 'korean', 'subwai'],
 ['dem', 'hold', 'plebiscit', 'iraqi', 'conflict'],
 ['dent', 'down', 'philippoussi', 'tie', 'break', 'thriller'],
 ['villier', 'learn', 'fate', 'march'],
 ['digit', 'commonplac', 'summit'],
 ['direct', 'anger', 'govt', 'soldier', 'crean', 'urg'],
 ['disput', 'smithton', 'veget', 'process', 'plant'],
 ['dog', 'maul', 'month', 'old', 'toddler', 'nsw'],
 ['dy', 'korean', 'subwai', 'passeng', 'phone', 'help'],
 ['england', 'chang', 'wale', 'match'],
 ['epa', 'try', 'recov', 'chemic', 'clean', 'cost'],
 ['express', 'sought', 'build', 'livestock'],
 ['fed', 'opp', 'introduc', 'nation', 'insur'],
 ['firefight', 'contain', 'acid', 'spill'],
 ['injur', 'head', 'highwai', 'crash'],
 ['freedom', 'record', 'net', 'profit', 'success'],
 ['fund', 'alloc', 'domest', 'violenc', 'victim'],
 ['fund', 'alloc', 'youth', 'risk'],
 ['fund', 'announc', 'bridg', 'work'],
 ['fund', 'cadel', 'upgrad'],
 ['fund', 'help', 'restor', 'cossack'],
 ['german', 'court', 'verdict', 'sept', 'accus'],
 ['gilchrist', 'back', 'rest', 'polici'],
 ['girl', 'injur', 'head', 'highwai', 'crash'],
 ['gold', 'coast', 'hear', 'bilbi', 'project'],
 ['golf', 'club', 'feel', 'smoke', 'ban', 'impact'],
 ['govt', 'blame', 'ethanol', 'unpopular', 'opp'],
 ['green', 'offer', 'polic', 'station', 'altern'],
 ['griffith', 'project', 'knock'],
 ['group', 'meet', 'north', 'west', 'rock', 'art'],
 ['hacker', 'gain', 'access', 'million', 'credit', 'card'],
 ['hanson', 'grossli', 'naiv', 'nsw', 'issu', 'costa'],
 ['hanson', 'came', 'nsw'],
 ['harrington', 'rare', 'break'],
 ['health', 'minist', 'back', 'organ', 'tissu', 'storag'],
 ['heavi', 'metal', 'deposit', 'survei', 'near', 'end'],
 ['injur', 'rio', 'pull', 'bueno', 'air', 'open'],
 ['inquest', 'find', 'man', 'death', 'accident'],
 ['investig', 'underwai', 'death', 'toll', 'korean'],
 ['investig', 'underwai', 'elster', 'creek', 'spill'],
 ['iraq', 'neighbour', 'plead', 'continu', 'inspect'],
 ['iraq', 'pai', 'rebuild', 'white', 'hous'],
 ['irish', 'man', 'arrest', 'omagh', 'bomb'],
 ['irrig', 'vote', 'river', 'manag'],
 ['isra', 'forc', 'push', 'gaza', 'strip'],
 ['juri', 'consid', 'verdict', 'murder', 'case'],
 ['juvenil', 'sex', 'offend', 'unlik', 'reoffend'],
 ['kelli', 'disgust', 'alleg', 'ethanol', 'scare'],
 ['kelli', 'surpris', 'ethanol', 'confid', 'low'],
 ['korean', 'subwai', 'miss'],
 ['minut', 'hand', 'alinghi', 'big', 'lead'],
 ['low', 'demand', 'forc', 'air', 'servic', 'cut'],
 ['man', 'arrest', 'central', 'qld', 'hijack', 'attempt'],
 ['man', 'charg', 'cooma', 'murder'],
 ['man', 'fine', 'aborigin', 'tent', 'embassi', 'raid'],
 ['man', 'jail', 'keno', 'fraud'],
 ['man', 'knife', 'hijack', 'light', 'plane'],
 ['martin', 'lobbi', 'lose', 'seat', 'fed'],
 ['massiv', 'drug', 'crop', 'discov', 'western', 'nsw'],
 ['mayor', 'warn', 'landfil', 'protest'],
 ['meet', 'consid', 'tick', 'clearanc', 'cost'],
 ['meet', 'focu', 'broken', 'hill', 'water', 'woe'],
 ['moder', 'lift', 'wage', 'growth'],
 ['young', 'men', 'drink', 'alcohol'],
 ['water', 'restrict', 'predict', 'northern', 'ta'],
 ['women', 'urg', 'councillor'],
 ['highli', 'educ', 'live', 'nsw'],
 ['rais', 'hospit', 'concern', 'parliament'],
 ['reject', 'ambul', 'levi', 'claim'],
 ['mugab', 'touch', 'pari', 'summit'],
 ['nation', 'galleri', 'get', 'clear'],
 ['nato', 'give', 'green', 'light', 'defend', 'turkei'],
 ['nca', 'defend', 'aborigin', 'tent', 'embassi', 'raid'],
 ['new', 'zealand', 'impos', 'visa', 'entri', 'zimbabw'],
 ['effect', 'new', 'whoop', 'cough', 'vaccin'],
 ['nsw', 'govt', 'hold', 'veget'],
 ['nsw', 'opp', 'defend', 'claim', 'run', 'race', 'campaign'],
 ['nsw', 'opp', 'pledg', 'drought', 'relief'],
 ['govt', 'boost', 'nurs', 'number', 'oversea', 'intak'],
 ['nth', 'korean', 'seek', 'asylum', 'japanes', 'embassi'],
 ['nurs', 'student', 'intak'],
 ['brother', 'time', 'sai', 'ganguli', 'senior'],
 ['omodei', 'stai', 'polit'],
 ['onesteel', 'invest', 'whyalla', 'steelwork'],
 ['opposit', 'urg', 'help', 'protect', 'recherch', 'bai'],
 ['orient', 'begin', 'uni', 'student'],
 ['osullivan', 'world', 'cross', 'countri', 'doubt'],
 ['pagan', 'sai', 'rule', 'chang', 'necessari'],
 ['pair', 'face', 'court', 'ayr', 'murder'],
 ['patterson', 'defend', 'decis', 'attend', 'health'],
 ['patterson', 'displai', 'govt', 'arrog', 'crean'],
 ['patterson', 'snub', 'health', 'meet', 'avoid', 'lion', 'den'],
 ['peac', 'agreement', 'bring', 'respit', 'venezuela'],
 ['pienaar', 'shine', 'ajax', 'frustrat', 'arsen'],
 ['plan', 'second', 'skatepark'],
 ['plan', 'encourag', 'farmer', 'plantat', 'timber'],
 ['png', 'nurs', 'strike', 'colleagu', 'rape', 'wai'],
 ['polic', 'crack', 'driver', 'safeti'],
 ['polic', 'defend', 'aborigin', 'tent', 'embassi', 'raid'],
 ['policewomen', 'accus', 'featur', 'feder', 'crime'],
 ['probe', 'launch', 'plane', 'crash'],
 ['program', 'monitor', 'forest', 'harvest', 'area'],
 ['public', 'urg', 'check', 'ga', 'cylind'],
 ['public', 'warn', 'phone', 'scam'],
 ['qanta', 'intern', 'crew', 'strike', 'pai'],
 ['qanta', 'war', 'plan', 'cut', 'job', 'outrag', 'union'],
 ['plan', 'northern', 'rout', 'sack'],
 ['question', 'public', 'anger', 'grow', 'korean', 'subwai'],
 ['rabbit', 'control', 'program', 'trial'],
 ['radioact', 'spill', 'wmc', 'olymp', 'dam'],
 ['rain', 'eas', 'wheatbelt', 'water', 'woe'],
 ['read', 'divis'],
 ['record', 'gladston', 'ventur'],
 ['refshaug', 'win', 'defam', 'court', 'case'],
 ['regul', 'inspect', 'canola', 'trial'],
 ['report', 'highlight', 'contain', 'termin', 'potenti'],
 ['resourc', 'stock', 'boost', 'ord'],
 ['restraint', 'order', 'issu', 'anti', 'discrimin'],
 ['rf', 'reject', 'claim', 'act', 'author', 'spurn'],
 ['ricciuto', 'undergo', 'surgeri', 'injur', 'ankl'],
 ['rice', 'closur', 'work'],
 ['rsl', 'angri', 'report', 'troop', 'harass'],
 ['safeti', 'review', 'begin', 'bushwalk', 'death'],
 ['premier', 'call', 'action', 'river', 'murrai'],
 ['saudi', 'arabian', 'stand', 'trial', 'qaeda'],
 ['saudi', 'arabia', 'tell', 'arab', 'war', 'iraq', 'inevit'],
 ['search', 'continu', 'victim', 'korean', 'subwai'],
 ['second', 'resolut', 'iraq', 'expect', 'shortli'],
 ['shire', 'offer', 'assur', 'financ'],
 ['palestinian', 'kill', 'gaza', 'incurs'],
 ['slow', 'recoveri', 'predict', 'aust', 'economi'],
 ['smoke', 'ban', 'hit', 'tabcorp', 'line'],
 ['snowtown', 'murder', 'trial', 'delai'],
 ['state', 'forc', 'label', 'ethanol', 'fuel'],
 ['station', 'fix', 'home', 'phone', 'servic'],
 ['sterrei', 'steer', 'shark'],
 ['sign', 'miss', 'fisherman'],
 ['stop', 'chang', 'rule', 'fan', 'tell', 'afl'],
 ['sugar', 'industri', 'plan', 'reveal'],
 ['surg', 'new', 'car', 'sale', 'aust', 'ab'],
 ['swiss', 'challeng', 'look', 'futur'],
 ['taipan', 'place', 'futur', 'public', 'hand'],
 ['talk', 'asian', 'nuclear', 'arm', 'race', 'unhelp', 'downer'],
 ['tasmanian', 'scientist', 'search', 'east', 'coast'],
 ['taylor', 'deni', 'call', 'waugh', 'quit'],
 ['teen', 'face', 'court', 'drug', 'charg'],
 ['test', 'show', 'dioxin', 'drink', 'water', 'standard'],
 ['thousand', 'rememb', 'anniversari', 'darwin'],
 ['union', 'ask', 'member', 'support', 'public', 'protest'],
 ['uni', 'continu', 'tree', 'diseas', 'studi'],
 ['british', 'aircraft', 'attack', 'sth', 'iraq', 'target'],
 ['vff', 'bui', 'stock', 'feed', 'pellet', 'affect'],
 ['vic', 'local', 'council', 'welcom', 'singl', 'poll', 'dai'],
 ['victorian', 'scientist', 'honour', 'award'],
 ['vowl', 'retir', 'end', 'season'],
 ['wale', 'coach', 'accus', 'player', 'belittl', 'red'],
 ['warn', 'hear', 'set', 'fridai'],
 ['webb', 'favourit', 'ladi', 'master'],
 ['widn', 'abandon', 'paul', 'bid'],
 ['wildlif', 'sanctuari', 'plan', 'reveal'],
 ['william', 'sai', 'tight', 'bowl', 'kei', 'warrior', 'win'],
 ['wine', 'chief', 'bounc', 'sack'],
 ['worksaf', 'probe', 'potato', 'harvest', 'injuri'],
 ['dead', 'rebel', 'bomb', 'raid', 'philippin', 'armi'],
 ['abattoir', 'sale'],
 ['academ', 'upbeat', 'higher', 'educ', 'review'],
 ['administr', 'appoint', 'land', 'council'],
 ['aec', 'declar', 'lose', 'parliamentari', 'seat'],
 ['amcor', 'record', 'solid', 'profit', 'result'],
 ['america', 'cup', 'fourth', 'race', 'cancel'],
 ['arsen', 'pois', 'swoop', 'beckham', 'report'],
 ['aust', 'drink', 'alcohol', 'smoke', 'studi'],
 ['austeel', 'ei', 'releas', 'soon', 'nsw', 'govt'],
 ['australian', 'flag', 'celebr', 'birthdai'],
 ['awu', 'hold', 'meet', 'port', 'kembla', 'job'],
 ['babi', 'badli', 'burnt', 'brisban', 'hous'],
 ['bad', 'weather', 'caus', 'iranian', 'plane', 'crash'],
 ['beckham', 'lead', 'man', 'cut', 'deplet', 'juve'],
 ['bewar', 'standard', 'alcohol', 'drink'],
 ['bilbi', 'dream', 'realiti'],
 ['brisban', 'sparki', 'head', 'dai', 'strike'],
 ['britain', 'tell', 'nation', 'leav', 'iraq', 'kuwait'],
 ['british', 'high', 'court', 'overturn', 'new', 'blair', 'asylum'],
 ['british', 'magician', 'entomb', 'chees'],
 ['bungl', 'leav', 'doctor', 'wait', 'practis'],
 ['bushfir', 'coroni', 'inquiri', 'wind'],
 ['bush', 'thank', 'nato', 'support', 'turkei'],
 ['ambo', 'help', 'wake', 'fund', 'chang'],
 ['canegrow', 'hope', 'late', 'summer', 'rain'],
 ['capriati', 'hungri', 'dubai'],
 ['celt', 'underdog', 'uefa', 'clash', 'oneil'],
 ['chamber', 'vow', 'smash', 'world', 'mark'],
 ['charvi', 'pai', 'penalti', 'humphrei', 'earn', 'shock'],
 ['christma', 'detent', 'centr', 'claim', 'quash'],
 ['claim', 'defenc', 'spend', 'prioriti', 'health'],
 ['claim', 'educ', 'polici', 'caus', 'high', 'indigen'],
 ['claim', 'new', 'code', 'protect', 'autopsi', 'consent'],
 ['claim', 'ta', 'educ', 'polici', 'caus', 'high', 'indigen'],
 ['colleg', 'continu', 'work', 'experi'],
 ['concern', 'act', 'probe', 'cover', 'legal'],
 ['concord', 'make', 'emerg', 'land', 'canada'],
 ['coroni', 'inquiri', 'expect', 'hospit', 'death'],
 ['council', 'chief', 'lament', 'job', 'advertis', 'decis'],
 ['council', 'gener', 'manag', 'step'],
 ['council', 'offer', 'vandal', 'report', 'reward'],
 ['countri', 'race', 'club', 'hold', 'tab', 'fear'],
 ['court', 'rule', 'longford', 'ga', 'compo', 'todai'],
 ['cristal', 'end', 'match', 'libertador', 'lose', 'streak'],
 ['cuper', 'slam', 'inter', 'bad', 'boi', 'recoba'],
 ['deportivo', 'slip', 'buoyant', 'swiss', 'minnow', 'basel'],
 ['distanc', 'swimmer', 'maronei', 'call', 'quit'],
 ['dixon', 'dismiss', 'qanta', 'monopoli', 'claim'],
 ['downer', 'warn', 'iraq', 'action', 'begin', 'soon'],
 ['drought', 'break', 'rain', 'month', 'awai'],
 ['drought', 'impact', 'far', 'reach'],
 ['drought', 'take', 'toll', 'insect'],
 ['earli', 'childhood', 'develop', 'receiv', 'research'],
 ['elli', 'webb', 'place', 'ladi', 'master'],
 ['employe', 'grant', 'restrain', 'order'],
 ['england', 'choke', 'burger', 'king'],
 ['england', 'morri', 'cap'],
 ['epa', 'investig', 'radioact', 'spill'],
 ['esso', 'respons', 'econom', 'loss', 'ga'],
 ['esso', 'win', 'class', 'action', 'longford', 'ga'],
 ['etienn', 'agre', 'tyson', 'fight'],
 ['famili', 'confront', 'korean', 'presid', 'elect'],
 ['fan', 'join', 'flower', 'olonga', 'anti', 'mugab', 'protest'],
 ['ferguson', 'hail', 'beckham', 'unit', 'victori'],
 ['fewer', 'australian', 'jail', 'ab'],
 ['fifa', 'boss', 'prepar', 'postpon', 'match', 'war'],
 ['firefight', 'told', 'attend', 'tip', 'blaze'],
 ['fish', 'clean', 'facil', 'plan', 'announc'],
 ['flight', 'attend', 'action', 'wont', 'affect', 'bundaberg'],
 ['forest', 'allianc', 'reject', 'hindranc', 'claim'],
 ['bank', 'worker', 'plead', 'guilti', 'theft', 'charg'],
 ['treasur', 'charg', 'start'],
 ['forum', 'put', 'focu', 'region', 'need'],
 ['nomin', 'nat', 'charter', 'tower', 'preselect'],
 ['franc', 'drop', 'merceron', 'gelez', 'face', 'scot'],
 ['french', 'expedit', 'site', 'heritag', 'protect'],
 ['fuel', 'price', 'jump', 'newcastl'],
 ['fulham', 'smash', 'west', 'brom', 'quickfir', 'trio'],
 ['ganguli', 'lead', 'india', 'victori'],
 ['gartner', 'wine', 'wound'],
 ['gippsland', 'firefight', 'remain', 'guard'],
 ['govt', 'canvass', 'wai', 'improv', 'child', 'develop'],
 ['govt', 'work', 'rhh', 'coron', 'suicid', 'report'],
 ['greenpeac', 'call', 'ban', 'canola'],
 ['green', 'dump', 'anti', 'terror', 'kit', 'howard', 'doorstep'],
 ['group', 'air', 'truanci', 'concern'],
 ['group', 'prais', 'outgo', 'opposit', 'agricultur'],
 ['group', 'reef', 'build'],
 ['hagan', 'blood', 'rooki', 'penrith'],
 ['houllier', 'back', 'owen', 'break', 'rush', 'score', 'record'],
 ['howard', 'step', 'critic', 'anti', 'war', 'protest'],
 ['howard', 'vow', 'stai', 'iraq', 'crisi'],
 ['hussein', 'sai', 'iraq', 'doesnt', 'want', 'war'],
 ['illeg', 'fish', 'hot', 'spot', 'identifi'],
 ['immigr', 'raid', 'melbourn', 'draw', 'flak'],
 ['impati', 'grow', 'water', 'manag', 'plan'],
 ['indi', 'meet', 'like', 'includ', 'rain', 'race', 'talk'],
 ['injuri', 'threaten', 'unit', 'final', 'bid'],
 ['sought', 'build', 'stage', 'bypass'],
 ['investig', 'underwai', 'qanta', 'skid'],
 ['investor', 'plan', 'ethanol', 'plant', 'lament', 'trial'],
 ['iran', 'militari', 'plane', 'crash', 'kill'],
 ['iran', 'plane', 'crash', 'aboard'],
 ['iraqi', 'us', 'human', 'shield', 'war', 'crime'],
 ['itali', 'remain', 'unchang', 'ireland', 'clash'],
 ['kalgoorli', 'boulder', 'crime', 'rate', 'declin'],
 ['kayak', 'rescu', 'second', 'dai', 'adventur'],
 ['kirwan', 'stick', 'win', 'formula', 'ireland'],
 ['korean', 'book', 'atp', 'date', 'seed', 'roddick'],
 ['landhold', 'contribut', 'discuss'],
 ['lawyer', 'allow', 'visit', 'manu', 'detent', 'centr'],
 ['lawyer', 'set', 'appeal', 'man', 'sept', 'convict'],
 ['lawyer', 'review', 'case', 'esso', 'appeal'],
 ['lend', 'leas', 'post', 'million', 'loss'],
 ['lethal', 'back', 'point', 'rule', 'chang'],
 ['airport', 'tunnel', 'remain', 'close', 'accid'],
 ['macarthur', 'kingfish', 'suffer', 'minor', 'damag'],
 ['man', 'apologis', 'plane', 'hijack'],
 ['man', 'await', 'sentenc', 'denmark', 'murder'],
 ['man', 'question', 'qld', 'backpack', 'death'],
 ['man', 'charg', 'roxbi', 'down', 'plane', 'incid'],
 ['man', 'hospit', 'stab', 'attack'],
 ['man', 'lose', 'defam', 'compo', 'bid'],
 ['man', 'murder', 'charg', 'refus', 'bail'],
 ['man', 'face', 'court', 'alleg', 'hijack'],
 ['man', 'face', 'court', 'attempt', 'arm', 'robberi'],
 ['man', 'whack', 'thatcher', 'get', 'month', 'jail'],
 ['maronei', 'call', 'quit'],
 ['medal', 'recognis', 'island', 'war', 'effort'],
 ['meet', 'consid', 'glenelg', 'river', 'futur'],
 ['melbourn', 'man', 'receiv', 'massiv', 'compo', 'payout'],
 ['mgladbach', 'leav', 'danger', 'zone', 'home', 'win'],
 ['rate', 'challeng', 'result', 'expect', 'march'],
 ['miner', 'explor', 'nickel', 'deposit'],
 ['molotov', 'cocktail', 'suspect', 'melb', 'hotel'],
 ['anti', 'war', 'ralli', 'plan'],
 ['land', 'noosa', 'nation', 'park'],
 ['teacher', 'danger', 'student', 'union'],
 ['detain', 'immigr', 'raid'],
 ['women', 'unlik', 'join', 'men', 'pga', 'master'],
 ['moslei', 'readi', 'engin', 'compromis'],
 ['motorist', 'avoid', 'ethanol', 'blend', 'fuel', 'labor'],
 ['mud', 'crab', 'busi'],
 ['murrai', 'meet', 'wouldnt', 'detract', 'ministeri'],
 ['nat', 'seek', 'probe', 'bushfir', 'probe'],
 ['new', 'boat', 'take', 'waterwai'],
 ['new', 'zealand', 'discov', 'kenya', 'fate', 'thursdai'],
 ['fund', 'discuss', 'nsw', 'poll'],
 ['penalti', 'church', 'damag', 'monument'],
 ['nsw', 'coalit', 'make', 'magic', 'pud', 'elect'],
 ['govt', 'announc', 'commun', 'benefit', 'grant'],
 ['offer', 'roll', 'classic', 'holden'],
 ['oil', 'price', 'hit', 'new', 'high'],
 ['oldfield', 'court', 'nation', 'pre'],
 ['nation', 'pre', 'select', 'hear', 'continu', 'nsw'],
 ['packer', 'hand', 'licenc', 'pistol', 'investig'],
 ['pakistani', 'air', 'forc', 'chief', 'kill', 'air', 'crash'],
 ['palaszczuk', 'wont', 'disast', 'fund', 'promis'],
 ['park', 'protect', 'high', 'conserv', 'area'],
 ['peac', 'group', 'deni', 'member', 'harass', 'soldier'],
 ['peopl', 'trap', 'pile'],
 ['pilot', 'make', 'emerg', 'land', 'adelaid', 'airport'],
 ['player', 'continu', 'zimbabw', 'protest'],
 ['critic', 'protest', 'disgrac', 'crean'],
 ['defend', 'critic', 'anti', 'war', 'protest'],
 ['polic', 'continu', 'probe', 'human', 'remain'],
 ['polic', 'second', 'cannabi', 'crop'],
 ['polic', 'hope', 'gain', 'edg', 'weapon', 'user'],
 ['polic', 'locat', 'miss', 'famili', 'hous'],
 ['polic', 'arrest', 'drug', 'raid'],
 ['polic', 'seek', 'help', 'pai', 'piraci'],
 ['polic', 'tax', 'offic', 'fight', 'chop', 'chop', 'trade'],
 ['polic', 'wont', 'rule', 'link', 'drug', 'plantat'],
 ['politician', 'breed', 'public', 'anti', 'troop', 'sentiment'],
 ['pollock', 'deni', 'split', 'protea', 'camp'],
 ['popul', 'drift', 'forc', 'new', 'feder', 'boundari'],
 ['powel', 'visit', 'asia', 'bid', 'eas', 'nth', 'korean'],
 ['predict', 'good', 'wheatbelt', 'rain'],
 ['probe', 'launch', 'fatal', 'polic', 'pursuit'],
 ['protest', 'condemn', 'howard', 'critic', 'anti', 'war'],
 ['protocol', 'follow', 'immigr', 'raid'],
 ['public', 'warn', 'snake', 'handl', 'danger'],
 ['pump', 'continu', 'richmond', 'flood'],
 ['qanta', 'draw', 'flak', 'redund', 'talk'],
 ['qanta', 'flag', 'job', 'cut', 'despit', 'record', 'profit'],
 ['qanta', 'record', 'million', 'profit'],
 ['qfvg', 'upset', 'retail', 'price'],
 ['qld', 'govt', 'sai', 'new', 'hospit', 'schedul'],
 ['qld', 'nat', 'close', 'deal', 'lib', 'springborg'],
 ['race', 'club', 'sneak', 'point', 'peru'],
 ['rain', 'boost', 'farmer', 'confid'],
 ['rain', 'forc', 'aussi', 'bowl', 'chang', 'buchanan'],
 ['ram', 'raid', 'target', 'newsag'],
 ['road', 'fund', 'tackl', 'flood'],
 ['ronaldo', 'put', 'real', 'race'],
 ['ruiz', 'hat', 'trick', 'guatemala', 'rout', 'nicaragua'],
 ['saff', 'gaug', 'feel', 'plan', 'crown', 'land'],
 ['safin', 'escud', 'rotterdam', 'comeback', 'trail'],
 ['govt', 'defend', 'move', 'forc', 'fine', 'default'],
 ['govt', 'appeal', 'fish', 'decis'],
 ['schmeichel', 'set', 'miss', 'arsen', 'trip'],
 ['school', 'reopen', 'paint', 'fume', 'scare'],
 ['scotland', 'refus', 'panic'],
 ['seaman', 'injuri', 'crisi', 'arsen'],
 ['self', 'clone', 'crayfish', 'threaten', 'nativ', 'speci'],
 ['socceroo', 'creep', 'world', 'rank'],
 ['solar', 'car', 'turn', 'head'],
 ['sport', 'task', 'forc', 'plan', 'begin'],
 ['start', 'america', 'cup', 'race', 'delai'],
 ['stone', 'stai', 'feder', 'liber', 'presid'],
 ['sun', 'need', 'good', 'downpour'],

In [ ]:
# https://radimrehurek.com/gensim/models/word2vec.html
from gensim.models import Word2Vec

headlines_w2v = Word2Vec(headlines, size=300, window=5, min_count=3, workers=2, sg=1, iter=5)

In [ ]:
vector_hello = headlines_w2v.wv['hello']
print(vector_hello)

[ 0.26516256  0.118976    0.0321806  -0.08269373  0.21500708 -0.08606787
  0.08581436 -0.01800354 -0.00599952 -0.03305794 -0.10068499  0.15063691
  0.05972402  0.1609203  -0.1348684   0.01158233 -0.02051328  0.2478055
  0.07394484 -0.09026707  0.05097166 -0.14658225 -0.00248791 -0.17888065
  0.02605011 -0.08876601  0.21304125  0.03288979  0.11237387 -0.05127468
  0.01771657 -0.01804331 -0.09846018  0.06209943  0.03789793 -0.03817468
  0.28549045 -0.0340614  -0.08270827 -0.13586201  0.02742733 -0.04785349
 -0.07355367  0.14948533  0.06841046  0.03399006  0.10308504 -0.19856484
  0.04790941  0.09173802 -0.18790503 -0.21130146  0.15283011  0.09960278
 -0.07044777 -0.05942011 -0.16684909  0.19939333  0.11869258 -0.09120892
 -0.07712554  0.00803655 -0.03963339 -0.2104446  -0.16538201  0.1759886
  0.13145989 -0.06889513  0.05574354 -0.00746968  0.11645184  0.00806702
  0.01716048  0.01360278  0.0145288  -0.24455911 -0.00620541  0.02254119
 -0.05975442 -0.0614868  -0.04708771  0.20364377  0.04948774 -0.08924492
  0.00638547  0.15032388 -0.04894278  0.05598513  0.11859827 -0.13962656
  0.10588712 -0.10498855  0.04545257  0.05696177 -0.04039226 -0.02925847
  0.11618213 -0.1102354   0.15082215  0.06640989 -0.00592324 -0.15832038
 -0.04796381  0.02117978  0.02969011  0.01099392 -0.02531286 -0.02901394
 -0.03756575 -0.07172194 -0.15122816 -0.11264197 -0.08013024  0.2063612
 -0.1171548  -0.07400093 -0.15375409  0.07902234  0.02163202 -0.03858943
  0.02054313  0.06328095  0.04460183  0.09859605  0.10304622 -0.0957448
 -0.03538925  0.04358193  0.08126613  0.04786738 -0.00468504 -0.07134166
  0.09021978  0.0235971  -0.09240451 -0.04358402 -0.04788075  0.08172656
 -0.00688371 -0.06103304  0.07381934  0.03724946  0.05368511 -0.09597272
  0.02553431 -0.12281468  0.01103674 -0.1001403   0.01539262 -0.00987904
 -0.10780849  0.07965206  0.1335783   0.0454147  -0.07890995 -0.17590764
 -0.00639282  0.07203198  0.00164333 -0.07833967  0.06703474  0.00910254
 -0.01486872 -0.02407107  0.04167728  0.02130849  0.02613905  0.22256728
 -0.01691863 -0.21317926  0.09613605 -0.17227356  0.18592736  0.11808835
 -0.00462112  0.06092783 -0.22350846  0.03527853  0.19926164  0.00462177
 -0.1063986   0.08242938 -0.04033452  0.18466835 -0.00808889 -0.12373231
 -0.00488906 -0.01230722 -0.08007891  0.02017285  0.01347093  0.05833191
 -0.06116382  0.06396508  0.22714852 -0.13056497  0.04099452 -0.1483871
  0.06240921  0.09398611  0.20562437  0.10578777 -0.09082671 -0.05557395
  0.06263529  0.00696703  0.03343951 -0.08096965  0.03783177  0.06392132
 -0.10667509  0.12074345 -0.1179017  -0.1561692   0.03392217  0.01491633
  0.07602335  0.02397186 -0.21804324  0.07254392 -0.04656949 -0.12335642
  0.00045188 -0.17404594 -0.10441463 -0.00847987 -0.00306016  0.00843969
 -0.01045914 -0.04982789  0.09696104  0.20802008 -0.03654684  0.00609055
 -0.13365787  0.01091599 -0.0566574   0.15159753  0.01148105 -0.15044373
 -0.04544836 -0.19210818 -0.09350842  0.08624304 -0.09607347  0.18667461
  0.10646813 -0.12213028 -0.21535508 -0.01669887  0.12114461 -0.00100107
 -0.01782389 -0.19464873  0.0190149   0.04791642 -0.02964593 -0.11872804
 -0.08395224 -0.10381214 -0.18132351  0.0249616  -0.05321288  0.06009264
  0.08917321 -0.01292573 -0.00261882  0.07493803 -0.08214569 -0.02954851
  0.13276045 -0.13991706 -0.11210092 -0.01062988 -0.1300748   0.15096755
  0.11277124  0.08595169  0.06939492 -0.05672653  0.10290898 -0.02377078
  0.00083834 -0.174922    0.05313396  0.04945258 -0.04386991  0.08929215
 -0.02132373 -0.07592768  0.03648879  0.07862861  0.18308626  0.09136347
 -0.10337636 -0.10336942 -0.03616267 -0.06866357 -0.01128051 -0.01998037]

In [ ]:
vector_blah = headlines_w2v.wv['blah']

KeyError: ignored

In [ ]:
# Let's check out some words that are most similar to given words
headlines_w2v.wv.most_similar('art')

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('artist', 0.6111363172531128),
 ('contemporari', 0.609722912311554),
 ('dega', 0.6009142994880676),
 ('galleri', 0.5754117369651794),
 ('biennal', 0.5731141567230225),
 ('artwork', 0.569890022277832),
 ('abstract', 0.566983699798584),
 ('shakespear', 0.5649625062942505),
 ('exhibit', 0.5649441480636597),
 ('storytel', 0.5567246675491333)]

In [ ]:
headlines_w2v.wv.most_similar('strike')

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('stoppag', 0.49861979484558105),
 ('walkout', 0.48769569396972656),
 ('sunbu', 0.46753185987472534),
 ('struck', 0.46146202087402344),
 ('redeploy', 0.4433152675628662),
 ('pullback', 0.4404434561729431),
 ('repercuss', 0.43233343958854675),
 ('donetsk', 0.4304194748401642),
 ('syst', 0.43030256032943726),
 ('southlink', 0.42835840582847595)]

In [ ]:
headlines_w2v.wv.most_similar('discuss')

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('canvass', 0.5383526086807251),
 ('disagre', 0.5333232283592224),
 ('analys', 0.5304692387580872),
 ('talk', 0.5217949151992798),
 ('outlin', 0.5078900456428528),
 ('speak', 0.503757894039154),
 ('spoke', 0.4975435137748718),
 ('tapp', 0.49621039628982544),
 ('brainstorm', 0.48886701464653015),
 ('hanoi', 0.48631229996681213)]

In [ ]:
headlines_w2v.wv.most_similar('franc')

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('spain', 0.6573668122291565),
 ('germani', 0.623799741268158),
 ('itali', 0.6194068193435669),
 ('argentina', 0.5822550058364868),
 ('switzerland', 0.5729649066925049),
 ('poland', 0.5678437948226929),
 ('croatia', 0.558087944984436),
 ('belgium', 0.55141282081604),
 ('montenegro', 0.5493476390838623),
 ('oman', 0.548648476600647)]

In [ ]:
headlines_w2v.wv.most_similar('pari')

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('brussel', 0.6069685816764832),
 ('salah', 0.6002417206764221),
 ('nice', 0.5927411317825317),
 ('stockholm', 0.5867799520492554),
 ('hamburg', 0.5865440964698792),
 ('berlin', 0.5718734860420227),
 ('munich', 0.5677695274353027),
 ('charleston', 0.5674251317977905),
 ('warsaw', 0.5667096376419067),
 ('copenhagen', 0.5554043054580688)]

In [ ]:
headlines_w2v.wv.most_similar(positive=['woman', 'king'], negative=['man'])

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('adulyadej', 0.33788618445396423),
 ('elcho', 0.32033830881118774),
 ('castlereagh', 0.3182172179222107),
 ('bhumibol', 0.31302547454833984),
 ('brampton', 0.3118525743484497),
 ('bruni', 0.3103606104850769),
 ('monarch', 0.30363380908966064),
 ('faro', 0.2981110215187073),
 ('samak', 0.29737091064453125),
 ('broadbridg', 0.2964540421962738)]

In [ ]:
headlines_w2v.wv.most_similar(positive=['franc','madrid'], negative=['pari'])

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('spain', 0.6119322776794434),
 ('germani', 0.5459380745887756),
 ('argentina', 0.5261667966842651),
 ('itali', 0.5232619047164917),
 ('lippi', 0.5221758484840393),
 ('portug', 0.5218712687492371),
 ('romania', 0.5178719758987427),
 ('sociedad', 0.5117971897125244),
 ('sevilla', 0.5106390714645386),
 ('mallorca', 0.507168173789978)]

## Yelp Reviews: Sentiment Analysis

The dataset is 1000 Yelp reviews, and the goal is to classify sentiment. 1 stands for positive sentiment, and 0 stands for negative sentiment.

From lab, our best classifier, logistic regression, produced an accuracy of 0.79 using bag-of-words.

In [ ]:
!gdown --id 1JT0iVEoxzapvk0LxR1EFCXv_SqN48Hhs

Downloading...
From: https://drive.google.com/uc?id=1JT0iVEoxzapvk0LxR1EFCXv_SqN48Hhs
To: /content/yelp_labelled.txt
100% 61.3k/61.3k [00:00<00:00, 22.3MB/s]

In [ ]:
yelp = pd.read_csv('yelp_labelled.txt', sep="\t", header=None)
yelp.columns = ['text', 'label']

In [ ]:
yelp.head(10)

                                                text  label
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1
5     Now I am getting angry and I want my damn pho.      0
6              Honeslty it didn't taste THAT fresh.)      0
7  The potatoes were like rubber and you could te...      0
8                          The fries were great too.      1
9                                     A great touch.      1

In [ ]:
print(np.sum(yelp.label)) # this shows that we have a balanced dataset---500 positive labels and 500 negative labels

500

### Preprocessing the Yelp Dataset

In [ ]:
import importlib
from gensim.parsing import preprocessing
importlib.reload(preprocessing)

yelp['tokenized'] = preprocessing.preprocess_documents(yelp['text'])

In [ ]:
yelp.head(20)

                                                 text  ...                                          tokenized
0                            Wow... Loved this place.  ...                                 [wow, love, place]
1                                  Crust is not good.  ...                                      [crust, good]
2           Not tasty and the texture was just nasty.  ...                             [tasti, textur, nasti]
3   Stopped by during the late May bank holiday of...  ...  [stop, late, bank, holidai, rick, steve, recom...
4   The selection on the menu was great and so wer...  ...                       [select, menu, great, price]
5      Now I am getting angry and I want my damn pho.  ...                      [get, angri, want, damn, pho]
6               Honeslty it didn't taste THAT fresh.)  ...                            [honeslti, tast, fresh]
7   The potatoes were like rubber and you could te...  ...  [potato, like, rubber, tell, ahead, time, kept...
8                           The fries were great too.  ...                                       [fri, great]
9                                      A great touch.  ...                                     [great, touch]
10                           Service was very prompt.  ...                                   [servic, prompt]
11                                 Would not go back.  ...                                                 []
12  The cashier had no care what so ever on what I...  ...                [cashier, care, end, wayyi, overpr]
13  I tried the Cape Cod ravoli, chicken,with cran...  ...  [tri, cape, cod, ravoli, chicken, cranberri, m...
14  I was disgusted because I was pretty sure that...  ...               [disgust, pretti, sure, human, hair]
15  I was shocked because no signs indicate cash o...  ...                         [shock, sign, indic, cash]
16                                Highly recommended.  ...                                [highli, recommend]
17             Waitress was a little slow in service.  ...                    [waitress, littl, slow, servic]
18  This place is not worth your time, let alone V...  ...                    [place, worth, time, let, vega]
19                               did not like at all.  ...                                             [like]

[20 rows x 3 columns]

In [ ]:
preprocessing.STOPWORDS # notice that a lot of negative words, like "not" and "never", which may be important to sentiment, are on the stop words list and therefore removed!

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides',
           'between',
           'beyond',
           'bill',
           'both',
           'bottom',
           'but',
           'by',
           'call',
           'can',
           'cannot',
           'cant',
           'co',
           'computer',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'did',
           'didn',
           'do',
           'does',
           'doesn',
           'doing',
           'don',
           'done',
           'down',
           'due',
           'during',
           'each',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'few',
           'fifteen',
           'fify',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'for',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'from',
           'front',
           'full',
           'further',
           'get',
           'give',
           'go',
           'had',
           'has',
           'hasnt',
           'have',
           'he',
           'hence',
           'her',
           'here',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'hers',
           'herself',
           'him',
           'himself',
           'his',
           'how',
           'however',
           'hundred',
           'i',
           'ie',
           'if',
           'in',
           'inc',
           'indeed',
           'interest',
           'into',
           'is',
           'it',
           'its',
           'itself',
           'just',
           'keep',
           'kg',
           'km',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'make',
           'many',
           'may',
           'me',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'more',
           'moreover',
           'most',
           'mostly',
           'move',
           'much',
           'must',
           'my',
           'myself',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'no',
           'nobody',
           'none',
           'noone',
           'nor',
           'not',
           'nothing',
           'now',
           'nowhere',
           'of',
           'off',
           'often',
           'on',
           'once',
           'one',
           'only',
           'onto',
           'or',
           'other',
           'others',
           'otherwise',
           'our',
           'ours',
           'ourselves',
           'out',
           'over',
           'own',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'quite',
           'rather',
           're',
           'really',
           'regarding',
           'same',
           'say',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'she',
           'should',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'so',
           'some',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'such',
           'system',
           'take',
           'ten',
           'than',
           'that',
           'the',
           'their',
           'them',
           'themselves',
           'then',
           'thence',
           'there',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'these',
           'they',
           'thick',
           'thin',
           'third',
           'this',
           'those',
           'though',
           'three',
           'through',
           'throughout',
           'thru',
           'thus',
           'to',
           'together',
           'too',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'under',
           'unless',
           'until',
           'up',
           'upon',
           'us',
           'used',
           'using',
           'various',
           'very',
           'via',
           'was',
           'we',
           'well',
           'were',
           'what',
           'whatever',
           'when',
           'whence',
           'whenever',
           'where',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'which',
           'while',
           'whither',
           'who',
           'whoever',
           'whole',
           'whom',
           'whose',
           'why',
           'will',
           'with',
           'within',
           'without',
           'would',
           'yet',
           'you',
           'your',
           'yours',
           'yourself',
           'yourselves'})

In [ ]:
preprocessing.DEFAULT_FILTERS # so let's remove remove_stopwords from DEFAULT_FILTERS

[<function gensim.parsing.preprocessing.<lambda>>,
 <function gensim.parsing.preprocessing.strip_tags>,
 <function gensim.parsing.preprocessing.strip_punctuation>,
 <function gensim.parsing.preprocessing.strip_multiple_whitespaces>,
 <function gensim.parsing.preprocessing.strip_numeric>,
 <function gensim.parsing.preprocessing.remove_stopwords>,
 <function gensim.parsing.preprocessing.strip_short>,
 <function gensim.parsing.preprocessing.stem_text>]

In [ ]:
preprocessing.DEFAULT_FILTERS.pop(5)

In [ ]:
preprocessing.DEFAULT_FILTERS # confirmed removed

[<function gensim.parsing.preprocessing.<lambda>>,
 <function gensim.parsing.preprocessing.strip_tags>,
 <function gensim.parsing.preprocessing.strip_punctuation>,
 <function gensim.parsing.preprocessing.strip_multiple_whitespaces>,
 <function gensim.parsing.preprocessing.strip_numeric>,
 <function gensim.parsing.preprocessing.strip_short>,
 <function gensim.parsing.preprocessing.stem_text>]

In [ ]:
yelp['tokenized'] = preprocessing.preprocess_documents(yelp['text'])

In [ ]:
yelp.head(20)

                                                 text  ...                                          tokenized
0                            Wow... Loved this place.  ...                            [wow, love, thi, place]
1                                  Crust is not good.  ...                                 [crust, not, good]
2           Not tasty and the texture was just nasty.  ...    [not, tasti, and, the, textur, wa, just, nasti]
3   Stopped by during the late May bank holiday of...  ...  [stop, dure, the, late, mai, bank, holidai, of...
4   The selection on the menu was great and so wer...  ...  [the, select, the, menu, wa, great, and, were,...
5      Now I am getting angry and I want my damn pho.  ...            [now, get, angri, and, want, damn, pho]
6               Honeslty it didn't taste THAT fresh.)  ...                [honeslti, didn, tast, that, fresh]
7   The potatoes were like rubber and you could te...  ...  [the, potato, were, like, rubber, and, you, co...
8                           The fries were great too.  ...                       [the, fri, were, great, too]
9                                      A great touch.  ...                                     [great, touch]
10                           Service was very prompt.  ...                         [servic, wa, veri, prompt]
11                                 Would not go back.  ...                                 [would, not, back]
12  The cashier had no care what so ever on what I...  ...  [the, cashier, had, care, what, ever, what, ha...
13  I tried the Cape Cod ravoli, chicken,with cran...  ...  [tri, the, cape, cod, ravoli, chicken, with, c...
14  I was disgusted because I was pretty sure that...  ...  [wa, disgust, becaus, wa, pretti, sure, that, ...
15  I was shocked because no signs indicate cash o...  ...       [wa, shock, becaus, sign, indic, cash, onli]
16                                Highly recommended.  ...                                [highli, recommend]
17             Waitress was a little slow in service.  ...                [waitress, wa, littl, slow, servic]
18  This place is not worth your time, let alone V...  ...  [thi, place, not, worth, your, time, let, alon...
19                               did not like at all.  ...                              [did, not, like, all]

[20 rows x 3 columns]

In [ ]:
# https://radimrehurek.com/gensim/models/word2vec.html
from gensim.models import Word2Vec

yelp_w2v = Word2Vec(yelp['tokenized'], size=150, window=5, min_count=3, workers=2, sg=1, iter=100)

In [ ]:
# There is no way right now to get the average vector per document, but we can create our own function to do that
def get_mean_vector(w2v, words):
    # Make sure words are in the vocabulary---remember, we had dropped all words that occurred less than 3 times in the corpus
    words = [word for word in words if word in w2v.wv.vocab]
    if len(words) >= 1:
        return np.mean(w2v.wv[words], axis=0)
    else:
        return "NC" # I usually use this to indicate no characters

In [ ]:
averaged_doc_vecs = []
y = []
for i, review in enumerate(yelp['tokenized']):
    vec = get_mean_vector(yelp_w2v, review)
    if vec != "NC":
        averaged_doc_vecs.append(vec)
        y.append(yelp.label[i])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """

In [ ]:
X = np.stack(averaged_doc_vecs, axis=0) # this stacks all the arrays together into one big array that we can use for training

In [ ]:
import random
seed_val = 48109
random.seed(seed_val)
np.random.seed(seed_val)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, shuffle=True)

### Logistic Regression

Logistic regression performed the best on the bag-of-words approach, achieving an accuracy of 0.79.

In [ ]:
from sklearn.metrics import classification_report

# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
from sklearn.linear_model import LogisticRegression

# Training the model. Notice the regularization is imposed by default. This is different from R.
logreg = LogisticRegression()
clf_logreg = logreg.fit(X_train, y_train)

y_preds_clf_logreg = clf_logreg.predict(X_test)

print(classification_report(y_test, y_preds_clf_logreg))

              precision    recall  f1-score   support

           0       0.74      0.78      0.76        88
           1       0.82      0.79      0.80       112

    accuracy                           0.79       200
   macro avg       0.78      0.78      0.78       200
weighted avg       0.79      0.79      0.79       200

### Gaussian Naive Bayes

In the lab, we used multinomial Naive Bayes. That achieved an accuracy of 0.79. Because we a continuous dense feature space, we use Gaussian Naive Bayes instead.

In [ ]:
# https://scikit-learn.org/stable/modules/naive_bayes.html
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
clf_nb = nb.fit(X_train, y_train)

y_preds_clf_nb = clf_nb.predict(X_test)

print(classification_report(y_test, y_preds_clf_nb))

              precision    recall  f1-score   support

           0       0.71      0.59      0.65        88
           1       0.72      0.81      0.76       112

    accuracy                           0.71       200
   macro avg       0.71      0.70      0.70       200
weighted avg       0.71      0.71      0.71       200

### Linear Discriminant Analysis

In the bag-of-words example, LDA performed quite terribly. It had an accuracy of 0.61. That's because LDA usually works terribly with sparse matrices. But with word vectors, we now have dense vectors.

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
clf_lda = lda.fit(X_train, y_train)

y_preds_clf_lda = clf_lda.predict(X_test)

print(classification_report(y_test, y_preds_clf_lda))

              precision    recall  f1-score   support

           0       0.73      0.82      0.77        88
           1       0.84      0.77      0.80       112

    accuracy                           0.79       200
   macro avg       0.79      0.79      0.79       200
weighted avg       0.80      0.79      0.79       200

### Support Vector Machines

SVM had an accuracy of 0.74 on the bag-of-words example. Let's see how SVM does with the word embeddings.

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
from sklearn.svm import SVC

sv = SVC()
clf_sv = sv.fit(X_train, y_train)

y_preds_clf_sv = clf_sv.predict(X_test)

print(classification_report(y_test, y_preds_clf_sv))

              precision    recall  f1-score   support

           0       0.71      0.82      0.76        88
           1       0.84      0.74      0.79       112

    accuracy                           0.78       200
   macro avg       0.78      0.78      0.77       200
weighted avg       0.78      0.78      0.78       200

I bet we can do better---let's use cross-validation.

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html
from sklearn.model_selection import GridSearchCV

tuning_params = {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.01, 0.1, 1, 10]}

sv_gridsearch = GridSearchCV(SVC(), tuning_params)
sv_gridsearch_fit = sv_gridsearch.fit(X_train, y_train)
print(sv_gridsearch_fit.best_params_) # this will tell us the best params

{'C': 10, 'gamma': 0.1}

In [ ]:
y_preds_clf_sv_gridsearch = sv_gridsearch_fit.best_estimator_.predict(X_test)

print(classification_report(y_test, y_preds_clf_sv_gridsearch))

              precision    recall  f1-score   support

           0       0.77      0.86      0.81        88
           1       0.88      0.79      0.84       112

    accuracy                           0.82       200
   macro avg       0.82      0.83      0.82       200
weighted avg       0.83      0.82      0.83       200

### Fully-Connected Neural Network

Lastly, we look at the fully-connected neural network. Scikit-learn has an easy-to-use neural network module. The most important part of the classifier is setting the hidden layer sizes. Below, we use three hidden layers with the first layer being 450 hidden units, the second layer being 600 hidden units, and the third layer being 450 hidden units. These numbers were chosen arbitrarily; play around and see if you can do better.

In [ ]:
# https://scikit-learn.org/stable/modules/neural_networks_supervised.html
from sklearn.neural_network import MLPClassifier

nn_clf = MLPClassifier(solver='adam', hidden_layer_sizes=(450,600,450))
nn_clf.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(450, 600, 450), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
y_preds_clf_nn = nn_clf.predict(X_test)

print(classification_report(y_test, y_preds_clf_nn))

              precision    recall  f1-score   support

           0       0.77      0.90      0.83        88
           1       0.91      0.79      0.85       112

    accuracy                           0.84       200
   macro avg       0.84      0.85      0.84       200
weighted avg       0.85      0.84      0.84       200

### Standardization of Word Embedding Features

In [ ]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

X_train_scaled = std_scaler.fit_transform(X_train)

In [ ]:
X_test_scaled = std_scaler.transform(X_test)

nn_clf = MLPClassifier(solver='adam', hidden_layer_sizes=(450,600,450))
nn_clf.fit(X_train_scaled, y_train)

y_preds_clf_nn = nn_clf.predict(X_test_scaled)

print(classification_report(y_test, y_preds_clf_nn))

              precision    recall  f1-score   support

           0       0.76      0.84      0.80        88
           1       0.86      0.79      0.83       112

    accuracy                           0.81       200
   macro avg       0.81      0.82      0.81       200
weighted avg       0.82      0.81      0.82       200